# Configuration for GitHub CLI (gh) hosts.
# This file defines settings for different GitHub hosts.
github.com:
  # git_protocol: Specifies the protocol to use for git operations (e.g., clone, fetch).
  # Default: https
  git_protocol: https
  # users: A list of users associated with this host.
  # Default: Empty list (no default users)
  users:
    luiz1361:
  # user: The default user for this host when authenticating.
  # Default: None (prompts for user if not set)
  user: luiz1361
